print("Welcome to Madlibs Fun")

def start():
    print ("Pick a story")
    print ("Funny vacation story: press 1")
    print ("Worst bedtime story: press 2")
    print ("Love story: press 3 ")
    story = input('story: ')
    if story == '1': 
        adjective1=input("type an adjective: ")
        adjective2=input("type an adjective: ")
        noun1=input("type a noun: ")
        noun2=input("type a noun: ")
        pluralnoun1=input("type a plural noun: ")
        game=input("name a game: ")
        pluralnoun2=input("type a plural noun: ")
        verb1=input("type a verb ending in 'ing': ")
        verb2=input("type a verb ending in 'ing': ")
        pluralnoun3=input("type a plural noun: ")
        verb3=input("type a verb ending in 'ing': ")
        noun3=input("type a noun: ")
        plant=input("name a type of plant: ")
        partofbody=input("name a body part: ")
        place=input("name a place: ")
        verb4=input("type a verb ending in 'ing': ")
        adjective3=input("name a adjective: ")
        number=input("type a number: ")
        pluralnoun4=input("type a plural noun: ")
        print("A vacation is when you take a trip to some", adjective1, "place with your", adjective2)
    elif story == '2':    
        place1=input("type a place: ")
        adjective1=input("type an adjective: ")
        femalecel=input("type a female celebrity: ")
        bodypart1=input("type a body part: ")
        bodypart2=input("type a body part: ")
        organ=input("type a human organ: ")
        adjective2=input("type an adjective: ")
        malecel=input("type a male celebrity: ")
        adjective2=input("type an adjective: ")
        bodypart3=input("type a body part: ")
        bodypart4=input("type a body part: ")
        place2=input("type a place: ")
        celebrity=input("type a celebrity")
        animal=input("type an animal: ")
        verb=input("type a verb: ")
        number=input("type a number: ")
        bodypart5=input("type a body part: ")
        adjective3=input("type an adjective: ")
        adjective4=input("type an adjective: ")
        pastverb=input("type a past tense verb: ")
        print("Once upon a time, in a place called", place1, "there was a", adjective1, "princess named", femalecel, "." "Her kingdom was huge, but her" ,bodypart1)
        
        
    elif story=='3':
        
    else:
        print('Not a valid character')
start()
