print("Welcome to Madlibs Fun")

def start():
    print ("Pick a story")
    print ("Funny vacation story: press 1")
    print ("Worst bedtime story: press 2")
    print ("Love story: press 3 ")
    story = input('story: ')
    if story == '1': 
        adjective1=input("type an adjective: ")
        adjective2=input("type an adjective: ")
        noun1=input("type a noun: ")
        noun2=input("type a noun: ")
        pluralnoun1=input("type a plural noun: ")
        game=input("name a game: ")
        pluralnoun2=input("type a plural noun: ")
        verb1=input("type a verb ending in 'ing': ")
        verb2=input("type a verb ending in 'ing': ")
        pluralnoun3=input("type a plural noun: ")
        verb3=input("type a verb ending in 'ing': ")
        noun3=input("type a noun: ")
        plant=input("name a type of plant: ")
        partofbody=input("name a body part: ")
        place=input("name a place: ")
        verb4=input("type a verb ending in 'ing': ")
        adjective3=input("name a adjective: ")
        number=input("type a number: ")
        pluralnoun4=input("type a plural noun: ")
        print("A vacation is when you take a trip to some", adjective1, "place with your", adjective2, "family. Usually you go to some place that is near a/an", noun1, "or up on a/an", noun2, ". A good vacation place is one where you can ride", pluralnoun1, "or play", game,"or go hunting for",pluralnoun2,". I like to spend my time", verb1, "or", verb2, ". When parents go on vacation, they spend their time eating three", pluralnoun3, "a day, and fathers play golf, and mothers sit around", ver3, ". Last summer, my little brother fell in a/an", noun3, "and got poison", plant, "all over his", partofbody,". My family is going to go to (the)", place, ", and I will practice" ,verb4, ". Parents need vacations more than kids because parents are always very", adjective4, "and because they have to work", number,"hours every day all year making enough", pluralnoun4, "to pay for the vacation."
    elif story == '2':    
        place1=input("type a place: ")
        adjective1=input("type an adjective: ")
        femalecel=input("type a female celebrity: ")
        bodypart1=input("type a body part: ")
        bodypart2=input("type a body part: ")
        organ=input("type a human organ: ")
        adjective2=input("type an adjective: ")
        malecel=input("type a male celebrity: ")
        adjective2=input("type an adjective: ")
        bodypart3=input("type a body part: ")
        bodypart4=input("type a body part: ")
        place2=input("type a place: ")
        celebrity=input("type a celebrity")
        animal=input("type an animal: ")
        verb=input("type a verb: ")
        number=input("type a number: ")
        bodypart5=input("type a body part: ")
        adjective3=input("type an adjective: ")
        adjective4=input("type an adjective: ")
        pastverb=input("type a past tense verb: ")
        print("Once upon a time, in a place called", place1, "there was a", adjective1, "princess named", femalecel, "." "Her kingdom was huge, but her" ,bodypart1)    
    elif story=='3':
        print("hello")
    else:
        print("not a valid character")
    
 start()

